http:
  port: 6080
admin:
  port: 9876
  host: 182.70.249.165
apiEndpoints:
  api:
    host: 192.168.1.235
    paths: "/ip"
  user:
    host: 192.168.1.235
    paths: ["/users", "/users/*"]
  crud:
    host: 192.168.1.235
    paths: ["/crud", "/crud/*"]
  transaction:
    host: 192.168.1.235
    paths: ["/transaction", "/transaction/*"]
serviceEndpoints:
  httpbin:
    url: "http://182.70.249.165:60:9876"
  userService:
    url: "http://192.168.1.235:6081"
  crudService:
    url: "http://192.168.1.235:6082"
  transactionService:
    url: "http://192.168.1.235:6083"
policies:
  - proxy
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  userPipeline:
    apiEndpoints:
      - user
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
  crudPipeline:
    apiEndpoints:
      - crud
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: crudService
              changeOrigin: true
  transactionPipeline:
    apiEndpoints:
      - transaction
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: transactionService
              changeOrigin: true
